server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hmily_fx2?serverTimezone=Australia/Brisbane&useSSL=false
    username: test
    password: 123456

mybatis:
  type-aliases-package: com.wymansstudio.dubbo.boot.userVip.entity

dubbo:
  application:
    id: fx_provider
    name: fx_provider
  registry:
    address: zookeeper://127.0.0.1:2181
  metadata-report:
    address: zookeeper://localhost:2181
  protocol:
    port: 20000
    name: dubbo

  monitor:
    protocol: registry
