
spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/ecom?rewriteBatchedStatements=true
#    username: test
#    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  shardingsphere:
    schema:
      name: ecom
    datasource:
      names: m1-1,m1-2
      m1-1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3316/ecom1?rewriteBatchedStatements=true
        username: test
        password: 123456
      m1-2:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3316/ecom2?rewriteBatchedStatements=true
        username: test
        password: 123456
#      s1-1:
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        jdbc-url: jdbc:mysql://localhost:3326/ecom1?rewriteBatchedStatements=true
#        username: test
#        password: 123456
#      s1-2:
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        jdbc-url: jdbc:mysql://localhost:3326/ecom2?rewriteBatchedStatements=true
#        username: test
#        password: 123456
    props:
      sql:
        show: true
    sharding:
      tables:
        orders:
          actual-data-nodes: m1-$->{1..2}.orders$->{1..16}
          key-generator:
            column: orderid
            type: SNOWFLAKE
          table-strategy:
            inline:
              sharding-column: orderid
              algorithm-expression: orders$->{orderid % 2 + 1}
          database-strategy:
            inline:
              sharding-column: customerid
              algorithm-expression: m1-$->{customerid % 2 + 1}

#    masterslave:
#      name: ms
#      master-data-source-name: m1
#      slave-data-source-names: s1

#client-a:
#  datasource:
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:3316/ecom?rewriteBatchedStatements=true
#    username: test
#    password: 123456
#
#client-b:
#  datasource:
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:3326/ecom?rewriteBatchedStatements=true
#    username: test
#    password: 123456

